const urls = {
  firmaLogo: '/images/ic_firma_logo.svg',
  firmaLogo2: '/images/ic_firma_logo2.svg',
  firmaLogo3: '/images/ic_firma_logo3.svg',
  osmosisLogo: '/images/ic_osmosis_logo.svg',
  osmosisLogo2: '/images/ic_osmosis_logo2.png',
  osmosisLogo3: '/images/ic_osmosis_logo3.svg',
  collaborationX: '/images/ic_x.svg',
  mainSectionBg: '/images/img_main_section_bg.png',
  poolFctOsmo: '/images/img_pool_fct_osmo.png',
  poolAtomFct: '/images/img_pool_atom_fct.png',
  exchange: '/images/ic_exchange.svg',
  downArrow: '/images/ic_down_arrow.svg',
  rightArrow: '/images/ic_right.svg',
  external: '/images/ic_external.svg',
  socialMedium: '/images/ic_medium.svg',
  socialTwitter: '/images/ic_twitter.svg',
  socialTelegram: '/images/ic_telegram.svg',
  chart: '/images/img_chart.png',
  guideLogo: '/images/img_guide_logo.png',
  guide1: '/images/img_guide_1.png',
  guide2: '/images/img_guide_2.png',
  guide3: '/images/img_guide_3.png',
  guide4: '/images/img_guide_4.png',
  guide5: '/images/img_guide_5.png',
  guideLeft: '/images/img_guide_left.png',
  guideRight: '/images/img_guide_right.png',
  introBg: '/images/img_intro_bg.png',
  introLink1: '/images/ic_intro_link1.svg',
  introLink2: '/images/ic_intro_link2.svg',
  introLink3: '/images/ic_intro_link3.svg',
  keplr: '/images/ic_keplr.svg',
  coinList: [
    'images/ic_coin_1.png',
    'images/ic_coin_2.png',
    'images/ic_coin_3.png',
    'images/ic_coin_4.png',
    'images/ic_coin_5.png',
    'images/ic_coin_6.png',
    'images/ic_coin_7.png',
    'images/ic_coin_8.png',
    'images/ic_coin_9.png',
    'images/ic_coin_10.png',
    'images/ic_coin_11.png',
    'images/ic_coin_12.png',
    'images/ic_coin_13.png',
    'images/ic_coin_14.png',
  ],
};

export default urls;
